(()=>{'use strict';
if(window.__SG_MUSIC_FIX_V3__)return;window.__SG_MUSIC_FIX_V3__=true;
const STYLE=`#sgMusicShade{position:fixed;inset:0;background:#0009;z-index:2147482998;display:none;align-items:flex-end}#sgMusicShade.on{display:flex}#sgMusicSheet{width:100%;max-width:760px;margin:auto;background:#fff;border-radius:22px 22px 0 0;padding:12px;max-height:92vh;overflow:auto}#sgMusicSheet .mh{display:flex;align-items:center;justify-content:space-between;font-weight:900;padding:4px 2px 10px}#sgMusicSheet .mh button,#sgMusicFloat .mh button{border:0;border-radius:10px;padding:8px 10px;font-weight:800;background:#eee}#sgMusicSheet .mv,#sgMusicFloat .mv{position:relative;padding-top:56.25%;background:#000;border-radius:14px;overflow:hidden}#sgMusicFrame{position:absolute;inset:0;width:100%;height:100%;border:0}#sgMusicFloat{position:fixed;right:12px;bottom:86px;width:min(360px,calc(100vw - 24px));z-index:2147483000;background:#11162a;color:#fff;border-radius:16px;box-shadow:0 18px 55px #0008;overflow:hidden;display:none}#sgMusicFloat.on{display:block}#sgMusicFloat .mh{display:flex;align-items:center;justify-content:space-between;padding:8px 10px;font-weight:800;font-size:12px}#sgMusicFloat .mh button{background:#ffffff18;color:#fff}#sgMusicInput{display:flex;gap:7px;margin:4px 0 10px}#sgMusicInput input{flex:1;padding:11px;border:1px solid #e5e6ef;border-radius:11px;min-width:0}#sgMusicInput button{border:0;border-radius:11px;padding:10px 12px;background:#5b4bdb;color:#fff;font-weight:800}.sgMusicHint{font-size:12px;color:#73778c;line-height:1.45;margin:0 0 10px}`;
const st=document.createElement('style');st.textContent=STYLE;document.head.appendChild(st);
let shade=null,float=null,frame=null,videoId=null,openState=false;
function cleanDashboardMusic(){document.querySelectorAll('.icons .ico').forEach(el=>{const txt=(el.innerText||el.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();if(/music\s*&?\s*entertainment|music\s+and\s+entertainment/.test(txt))el.remove()});}
function build(){if(shade)return;
 shade=document.createElement('div');shade.id='sgMusicShade';shade.innerHTML='<div id="sgMusicSheet"><div class="mh"><span>🎬 Video • Silai Guru</span><div><button id="sgMusicMin">⌄ Mini Player</button> <button id="sgMusicClose">✕</button></div></div><p class="sgMusicHint">YouTube link ya search Silai Guru ke andar hi rahega. Search ke liye YouTube Data API key ek baar save karein.</p><div id="sgMusicInput"><input id="sgMusicUrl" type="text" placeholder="YouTube link ya search, jaise old songs"><button id="sgMusicPlay">▶ Play / Search</button></div><div class="sgYtKey"><input id="sgYtKey" type="password" placeholder="YouTube Data API key"><button id="sgYtSave">💾 Save</button></div><div id="sgYtResults" class="sgYtResults"></div><div class="sgYtSize"><button data-sgsize="50">50%</button><button data-sgsize="75">75%</button><button data-sgsize="100">100%</button><button id="sgYtFull">⛶ Full</button></div><div class="mv" id="sgMusicMainBox"></div></div></div>';
 document.body.appendChild(shade);
 float=document.createElement('div');float.id='sgMusicFloat';float.innerHTML='<div class="mh"><span>🎵 Silai Guru • Playing</span><button id="sgMusicMax">Open</button></div><div class="mv" id="sgMusicMiniBox"></div>';
 document.body.appendChild(float);
 frame=document.createElement('iframe');frame.id='sgMusicFrame';frame.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;frame.setAttribute('playsinline','');
 shade.querySelector('#sgMusicPlay').onclick=()=>{const q=shade.querySelector('#sgMusicUrl').value.trim();if(!q){alert('YouTube video link ya search text dijiye.');return}const id=idFrom(q);if(id){openVideo(id);return}searchYT(q)};shade.querySelector('#sgYtSave').onclick=()=>{const k=shade.querySelector('#sgYtKey').value.trim();if(!k){alert('API key dijiye.');return}localStorage.setItem('sg_youtube_api_key',k);alert('YouTube API key save ho gayi ✓')};shade.querySelectorAll('[data-sgsize]').forEach(b=>b.onclick=()=>{const box=shade.querySelector('#sgMusicMainBox .mvInner')||shade.querySelector('#sgMusicMainBox');box.style.width=b.dataset.sgsize+'%';box.style.margin='0 auto'});shade.querySelector('#sgYtFull').onclick=()=>{const box=shade.querySelector('#sgMusicMainBox');if(box.requestFullscreen)box.requestFullscreen()};shade.querySelector('#sgYtResults').onclick=e=>{const x=e.target.closest('[data-sgid]');if(x)openVideo(x.dataset.sgid)};
 shade.querySelector('#sgMusicMin').onclick=minimize;
 shade.querySelector('#sgMusicClose').onclick=closeAll;
 float.querySelector('#sgMusicMax').onclick=maximize;
}
function esc(s){return String(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}function idFrom(url){try{const u=new URL(String(url||'').trim(),location.href);let m=null;if(u.hostname==='youtu.be'||u.hostname.endsWith('.youtu.be'))m=u.pathname.split('/').filter(Boolean)[0];if(!m&&/youtube\.com$/i.test(u.hostname.replace(/^www\./,'')))m=u.searchParams.get('v');if(!m)m=(u.pathname.match(/\/(?:embed|shorts|live)\/([^/?#]+)/)||[])[1];return m?m.replace(/[^A-Za-z0-9_-]/g,'').slice(0,20):null}catch(e){return null}}
function mount(box){if(frame&&box){box.innerHTML='';box.appendChild(frame)}}
async function searchYT(q){build();const box=shade.querySelector('#sgYtResults');box.innerHTML='<div class="sgMusicHint">YouTube search ho raha hai…</div>';const bases=['https://inv.nadeko.net','https://invidious.nerdvpn.de','https://yt.artemislena.eu','https://invidious.private.coffee'];let last='';for(const base of bases){try{const r=await fetch(base+'/api/v1/search?q='+encodeURIComponent(q)+'&page=1');if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();const a=(d||[]).filter(x=>x.type==='video'&&x.videoId);if(!a.length)continue;box.innerHTML=a.slice(0,10).map(x=>{const th=(x.videoThumbnails||[]).sort((p,z)=>(z.width||0)-(p.width||0))[0]?.url||'';return '<div class="sgYtResult" data-sgid="'+String(x.videoId).replace(/[^A-Za-z0-9_-]/g,'')+'"><img src="'+th+'"><div><b>'+esc(x.title)+'</b><small>'+esc(x.author||'YouTube')+'</small></div></div>'}).join('');return}catch(e){last=e.message}}box.innerHTML='<div class="sgMusicHint">Search service abhi available nahi hai. Dobara try karein.<br>'+esc(last)+'</div>'}function openVideo(id){if(!id)return;build();videoId=id;const src='https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?rel=0&playsinline=1&enablejsapi=1';frame.src=src;mount(shade.querySelector('#sgMusicMainBox'));shade.classList.add('on');float.classList.remove('on');openState=true;shade.querySelector('#sgYtKey').value=localStorage.getItem('sg_youtube_api_key')||'';if(location.hash!=='#sg-music'){history.pushState({sgMusic:1},'',location.pathname+location.search+'#sg-music')}}
function minimize(){if(!videoId||!frame)return;mount(float.querySelector('#sgMusicMiniBox'));shade.classList.remove('on');float.classList.add('on');openState=false}
function maximize(){if(!videoId||!frame)return;mount(shade.querySelector('#sgMusicMainBox'));shade.classList.add('on');float.classList.remove('on');openState=true}
function closeAll(){if(!shade)return;shade.classList.remove('on');float.classList.remove('on');openState=false;videoId=null;if(frame)frame.src='about:blank';if(location.hash==='#sg-music'||location.hash==='#sg-music-help')history.replaceState({},'',location.pathname+location.search)}
function findYouTubeId(el){const a=el?.closest?.('a,button,[role="button"]');if(!a)return null;const href=a.getAttribute('href')||a.dataset.videoUrl||'';return idFrom(href)||a.dataset.videoId||null}
function openChooser(){build();shade.classList.add('on');float.classList.remove('on');openState=true;if(location.hash!=='#sg-music'){history.pushState({sgMusicChooser:1},'',location.pathname+location.search+'#sg-music')}setTimeout(()=>shade.querySelector('#sgMusicUrl')?.focus(),50)}
document.addEventListener('click',e=>{const t=e.target;const id=findYouTubeId(t);if(id){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openVideo(id);return}const a=t.closest?.('a');if(a&&/youtube\.com|youtu\.be/i.test(a.href||'')){const id2=idFrom(a.href);if(id2){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openVideo(id2);return}}const el=t.closest?.('button,a');if(el){const txt=(el.innerText||el.textContent||'').trim().toLowerCase();if(txt.includes('youtube')&&!findYouTubeId(el)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openChooser();return}}},true);
window.sgOpenYouTubeVideo=openVideo;
addEventListener('popstate',()=>{if(openState&&videoId){minimize()}else if(openState){closeAll()}});
cleanDashboardMusic();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',cleanDashboardMusic);else setTimeout(cleanDashboardMusic,0);
setTimeout(cleanDashboardMusic,100);setTimeout(cleanDashboardMusic,500);setTimeout(cleanDashboardMusic,1500);
new MutationObserver(cleanDashboardMusic).observe(document.documentElement,{childList:true,subtree:true});
})();
