(()=>{'use strict';
if(window.__SG_MUSIC_FIX__)return;window.__SG_MUSIC_FIX__=true;
const STYLE=`#sgMusicFloat{position:fixed;right:12px;bottom:86px;width:min(360px,calc(100vw - 24px));z-index:2147483000;background:#11162a;color:#fff;border-radius:16px;box-shadow:0 18px 55px #0008;overflow:hidden;display:none}#sgMusicFloat.on{display:block}#sgMusicFloat .mh{display:flex;align-items:center;justify-content:space-between;padding:8px 10px;font-weight:800;font-size:12px}#sgMusicFloat .mh button{background:#ffffff18;color:#fff;border:0;border-radius:9px;padding:5px 9px}#sgMusicFloat .mv{position:relative;padding-top:56.25%;background:#000}#sgMusicFloat iframe{position:absolute;inset:0;width:100%;height:100%;border:0}#sgMusicShade{position:fixed;inset:0;background:#0009;z-index:2147482998;display:none;align-items:flex-end}#sgMusicShade.on{display:flex}#sgMusicSheet{width:100%;max-width:760px;margin:auto;background:#fff;border-radius:22px 22px 0 0;padding:10px 12px 14px}#sgMusicSheet .mh{display:flex;align-items:center;justify-content:space-between;font-weight:900;padding:6px 2px 10px}#sgMusicSheet button{border:0;border-radius:10px;padding:9px 12px;font-weight:800;background:#eee}#sgMusicSheet .mv{position:relative;padding-top:56.25%;background:#000;border-radius:14px;overflow:hidden}#sgMusicSheet iframe{position:absolute;inset:0;width:100%;height:100%;border:0}`;
const st=document.createElement('style');st.textContent=STYLE;document.head.appendChild(st);
let shade,float,iframe,videoId=null,openState=false;
function build(){if(shade)return;shade=document.createElement('div');shade.id='sgMusicShade';shade.innerHTML='<div id="sgMusicSheet"><div class="mh"><span>🎬 Video</span><button id="sgMusicMin">⌄ Minimize</button></div><div class="mv"><iframe id="sgMusicFrame" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div></div>';document.body.appendChild(shade);
float=document.createElement('div');float.id='sgMusicFloat';float.innerHTML='<div class="mh"><span>🎵 Silai Guru • Playing</span><button id="sgMusicMax">Open</button></div><div class="mv"><iframe id="sgMusicFloatFrame" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div>';document.body.appendChild(float);
shade.querySelector('#sgMusicMin').onclick=minimize;float.querySelector('#sgMusicMax').onclick=maximize;
}
function idFrom(url){try{const u=new URL(url,location.href);let m=u.hostname.includes('youtu.be')?u.pathname.slice(1):u.searchParams.get('v');if(!m)m=(u.pathname.match(/(?:embed|shorts)\/([^/?]+)/)||[])[1];return m?m.replace(/[^A-Za-z0-9_-]/g,''):null}catch(e){return null}}
function openVideo(id){if(!id)return;build();videoId=id;const src='https://www.youtube.com/embed/'+id+'?enablejsapi=1&rel=0';shade.querySelector('#sgMusicFrame').src=src;float.querySelector('#sgMusicFloatFrame').src=src;shade.classList.add('on');float.classList.remove('on');openState=true;history.pushState({sgMusicVideo:id},'',location.pathname+location.search+'#music-video');}
function minimize(){if(!videoId)return;shade.classList.remove('on');float.classList.add('on');openState=false;}
function maximize(){if(!videoId)return;shade.classList.add('on');float.classList.remove('on');openState=true;}
function closeAll(){shade?.classList.remove('on');float?.classList.remove('on');openState=false;}
function findYouTubeId(el){let a=el.closest('a,button,[role="button"]');if(!a)return null;const txt=(a.innerText||a.textContent||'').trim().toLowerCase();const href=a.getAttribute('href')||'';if(!txt.includes('youtube')&&!/youtu\.be|youtube\.com/i.test(href))return null;return idFrom(href)||a.dataset.videoId||null}
document.addEventListener('click',e=>{const t=e.target;const id=findYouTubeId(t);if(id){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openVideo(id);return;}const a=t.closest('a');if(a&&/youtube\.com|youtu\.be/i.test(a.href||'')){const id2=idFrom(a.href);if(id2){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openVideo(id2);}}},true);
window.sgOpenYouTubeVideo=openVideo;
addEventListener('popstate',e=>{if(openState){minimize();}});
// If the integrated YouTube button has no video URL, keep the app in place and show a helpful in-app chooser instead of sending the user to another app.
document.addEventListener('click',e=>{const a=e.target.closest('button,a');if(!a)return;const txt=(a.innerText||a.textContent||'').trim().toLowerCase();if(txt.includes('youtube')&&!findYouTubeId(a)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();build();shade.querySelector('.mh span').textContent='▶️ YouTube';shade.querySelector('.mv').innerHTML='<div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:24px;text-align:center;color:#fff;background:#11162a"><div><div style="font-size:18px;font-weight:900;margin-bottom:8px">YouTube app ko bahar nahi kholenge</div><div style="font-size:13px;opacity:.8;line-height:1.5">Video ka YouTube link Silai Guru ke Video section me daalkar isi app ke andar play karein. Android Back dabane par video mini-player me rahega.</div></div></div>';shade.classList.add('on');float.classList.remove('on');openState=true;history.pushState({sgMusicHelp:1},'',location.pathname+location.search+'#music-help');}},true);
})();
